version: "3"

volumes:
  postgres:
services:
  api:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    command: "air -c ./build/.air.toml"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/go/base
    tty: true
  db:
    image: postgres:12
    container_name: goCleanArchitectureDB
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
