version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    command: "air -c ./build/.air.toml"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/go/base
    tty: true
